#!/usr/bin/env python3
"""
GMP Report Generator
====================

Generates GMP reports for:
1. PR analysis (/pr command)
2. GMP task execution (/gmp command)

Reports are generated ON-DEMAND, not during analysis.

Usage (PR mode):
    python3 scripts/workflow/generate_gmp_report.py \
        --pr 51 \
        --title "Spring Cleaning TODO Tracking" \
        --adopted 11 --skipped 0 --realigned 0

Usage (GMP task mode):
    python3 scripts/workflow/generate_gmp_report.py \
        --task "Add singleton decorators" \
        --tier RUNTIME \
        --todo "T1|core/di.py|10-20|Insert|Add decorator" \
        --validation "py_compile|✅,ruff|✅,tests|✅"

Part of /pr and /gmp slash command automation.
Reference: ADR-0059 (Inline Analysis with Script-Generated Reports)
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path

__dora_meta__ = {
    "module_id": "scripts.workflow.generate_gmp_report",
    "stability": "stable",
    "api_version": "1.0.0",
}


def get_next_gmp_number(reports_dir: Path) -> int:
    """Find the next available GMP number."""
    pattern = re.compile(r"GMP-Report-(\d+)-")
    max_num = 0

    for f in reports_dir.glob("GMP-Report-*.md"):
        match = pattern.search(f.name)
        if match:
            num = int(match.group(1))
            max_num = max(max_num, num)

    return max_num + 1


def generate_pr_report(
    pr_number: int,
    title: str,
    adopted: int,
    skipped: int,
    realigned: int,
    tier: str = "RUNTIME",
    notes: str = "",
    author: str = "cryptoxdog",
    files_changed: int | None = None,
) -> tuple[str, str]:
    """Generate GMP report for PR analysis."""
    reports_dir = Path(__file__).parent.parent.parent / "reports"
    gmp_number = get_next_gmp_number(reports_dir)

    # Generate short description from title
    short_desc = "-".join(title.split()[:5]).replace("/", "-").replace(":", "")
    short_desc = re.sub(r"[^a-zA-Z0-9-]", "", short_desc)

    filename = f"GMP-Report-{gmp_number}-PR{pr_number}-{short_desc}.md"

    total = adopted + skipped + realigned
    if files_changed is None:
        files_changed = total

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M EST")
    confidence = 95 if skipped == 0 and realigned == 0 else 85

    content = f"""# GMP Report {gmp_number}: PR #{pr_number} — {title}

**Report:** `{filename}`
**Generated:** {timestamp}
**Author:** @{author}
**Files Changed:** {files_changed}
**Tier:** {tier}
**Overall Confidence:** {confidence}%

---

## Summary

| Metric | Count |
|--------|-------|
| Files Analyzed | {total} |
| ✅ Adopted | {adopted} |
| ❌ Skipped | {skipped} |
| 🔧 Realigned | {realigned} |

---

## Notes

{notes if notes else "No additional notes."}

---

## Report Metadata

- **GMP Number:** {gmp_number}
- **PR Number:** {pr_number}
- **Generated By:** generate_gmp_report.py (PR mode)
"""
    return filename, content


def generate_task_report(
    task: str,
    tier: str = "RUNTIME",
    todo_items: list[str] | None = None,
    validation: str = "",
    notes: str = "",
) -> tuple[str, str]:
    """Generate GMP report for task execution."""
    reports_dir = Path(__file__).parent.parent.parent / "reports"
    gmp_number = get_next_gmp_number(reports_dir)

    # Generate short description from task
    short_desc = "-".join(task.split()[:5]).replace("/", "-").replace(":", "")
    short_desc = re.sub(r"[^a-zA-Z0-9-]", "", short_desc)

    filename = f"GMP-Report-{gmp_number}-{short_desc}.md"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M EST")

    # Parse TODO items
    todo_table = ""
    if todo_items:
        todo_table = "| T# | File | Lines | Action | Description |\n"
        todo_table += "|----|------|-------|--------|-------------|\n"
        for i, item in enumerate(todo_items, 1):
            parts = item.split("|")
            if len(parts) >= 4:
                todo_table += (
                    f"| T{i} | `{parts[0]}` | {parts[1]} | {parts[2]} | {parts[3]} |\n"
                )

    # Parse validation results
    val_table = ""
    if validation:
        val_table = "| Check | Result |\n|-------|--------|\n"
        for check in validation.split(","):
            parts = check.split("|")
            if len(parts) == 2:
                val_table += f"| {parts[0]} | {parts[1]} |\n"

    content = f"""# GMP Report {gmp_number}: {task}

**Report:** `{filename}`
**Generated:** {timestamp}
**Tier:** {tier}

---

## TODO Plan (Executed)

{todo_table if todo_table else "No TODO items recorded."}

---

## Validation Results

{val_table if val_table else "No validation results recorded."}

---

## Notes

{notes if notes else "No additional notes."}

---

## Report Metadata

- **GMP Number:** {gmp_number}
- **Generated By:** generate_gmp_report.py (task mode)
"""
    return filename, content


def main():
    parser = argparse.ArgumentParser(
        description="Generate GMP report (PR or task mode)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # PR mode
    python3 scripts/workflow/generate_gmp_report.py \\
        --pr 51 --title "Fix Bug" --adopted 3

    # Task mode
    python3 scripts/workflow/generate_gmp_report.py \\
        --task "Add singleton decorators" \\
        --tier RUNTIME \\
        --todo "core/di.py|10-20|Insert|Add decorator" \\
        --validation "py_compile|✅,ruff|✅"
        """,
    )

    # Mode selection (mutually exclusive)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--pr", type=int, help="PR number (PR mode)")
    mode.add_argument("--task", type=str, help="Task description (task mode)")

    # Common args
    parser.add_argument(
        "--tier",
        type=str,
        default="RUNTIME",
        choices=["KERNEL", "RUNTIME", "INFRA", "UX"],
        help="Tier classification",
    )
    parser.add_argument("--notes", type=str, default="", help="Additional notes")
    parser.add_argument("--dry-run", action="store_true", help="Print without saving")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument(
        "--update-workflow", action="store_true", help="Also update workflow_state.md"
    )

    # PR mode args
    parser.add_argument("--title", type=str, help="PR title (PR mode)")
    parser.add_argument("--adopted", type=int, default=0, help="Files adopted")
    parser.add_argument("--skipped", type=int, default=0, help="Files skipped")
    parser.add_argument("--realigned", type=int, default=0, help="Files realigned")
    parser.add_argument("--author", type=str, default="cryptoxdog", help="PR author")
    parser.add_argument("--files", type=int, default=None, help="Total files")

    # Task mode args
    parser.add_argument(
        "--todo",
        type=str,
        action="append",
        help="TODO item: file|lines|action|desc (repeatable)",
    )
    parser.add_argument(
        "--validation",
        type=str,
        default="",
        help="Validation results: check|result,check|result",
    )

    args = parser.parse_args()

    # Generate report based on mode
    if args.pr:
        if not args.title:
            parser.error("--title required in PR mode")
        filename, content = generate_pr_report(
            pr_number=args.pr,
            title=args.title,
            adopted=args.adopted,
            skipped=args.skipped,
            realigned=args.realigned,
            tier=args.tier,
            notes=args.notes,
            author=args.author,
            files_changed=args.files,
        )
    else:
        filename, content = generate_task_report(
            task=args.task,
            tier=args.tier,
            todo_items=args.todo,
            validation=args.validation,
            notes=args.notes,
        )

    reports_dir = Path(__file__).parent.parent.parent / "reports"
    filepath = reports_dir / filename
    gmp_number = int(re.search(r"GMP-Report-(\d+)-", filename).group(1))

    if args.json:
        output = {
            "filename": filename,
            "filepath": str(filepath),
            "gmp_number": gmp_number,
            "pr_number": args.pr,
            "task": args.task,
        }
        print(json.dumps(output, indent=2))
        return

    if args.dry_run:
        print(f"Would create: {filepath}\n")
        print("--- Content ---")
        print(content)
        return

    # Save report
    filepath.write_text(content)
    print(f"✅ Report saved: {filepath}")
    print(f"   GMP Number: {gmp_number}")

    # Optionally update workflow_state.md
    if args.update_workflow:
        import subprocess

        script = Path(__file__).parent / "update_workflow_state.py"
        if args.pr:
            subprocess.run(
                [
                    "python3",
                    str(script),
                    "pr-complete",
                    "--pr",
                    str(args.pr),
                    "--gmp",
                    str(gmp_number),
                    "--adopted",
                    str(args.adopted),
                    "--skipped",
                    str(args.skipped),
                    "--realigned",
                    str(args.realigned),
                ]
            )
        else:
            subprocess.run(
                [
                    "python3",
                    str(script),
                    "gmp-complete",
                    "--gmp",
                    str(gmp_number),
                    "--status",
                    "pass",
                ]
            )


if __name__ == "__main__":
    main()
