#!/usr/bin/env python3
"""
GMP Report Generator
====================

Generates GMP reports from PR analysis data.
Reports are generated ON-DEMAND, not during analysis.

Usage:
    python3 scripts/workflow/generate_gmp_report.py \
        --pr 51 \
        --title "Spring Cleaning TODO Tracking" \
        --adopted 11 \
        --skipped 0 \
        --realigned 0 \
        --tier RUNTIME \
        --notes "23 TODOs tagged with GMP-100-122"

Reference: ADR-0059 (Inline Analysis with Script-Generated Reports)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path


def get_next_gmp_number(reports_dir: Path) -> int:
    """Find the next available GMP number."""
    pattern = re.compile(r"GMP-Report-(\d+)-")
    max_num = 0
    
    for f in reports_dir.glob("GMP-Report-*.md"):
        match = pattern.search(f.name)
        if match:
            num = int(match.group(1))
            max_num = max(max_num, num)
    
    return max_num + 1


def generate_report(
    pr_number: int,
    title: str,
    adopted: int,
    skipped: int,
    realigned: int,
    tier: str = "RUNTIME",
    notes: str = "",
    author: str = "cryptoxdog",
    files_changed: int | None = None,
) -> tuple[str, str]:
    """Generate GMP report content and filename."""
    
    reports_dir = Path(__file__).parent.parent.parent / "reports"
    gmp_number = get_next_gmp_number(reports_dir)
    
    # Generate short description from title
    short_desc = "-".join(title.split()[:5]).replace("/", "-").replace(":", "")
    short_desc = re.sub(r"[^a-zA-Z0-9-]", "", short_desc)
    
    filename = f"GMP-Report-{gmp_number}-PR{pr_number}-{short_desc}.md"
    
    total = adopted + skipped + realigned
    if files_changed is None:
        files_changed = total
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M EST")
    
    confidence = 95 if skipped == 0 and realigned == 0 else 85
    
    content = f"""# GMP Report {gmp_number}: PR #{pr_number} — {title}

**Report:** `{filename}`
**Generated:** {timestamp}
**Author:** @{author}
**Files Changed:** {files_changed}
**Tier:** {tier}
**Overall Confidence:** {confidence}%

---

## Summary

| Metric | Count |
|--------|-------|
| Files Analyzed | {total} |
| ✅ Adopted | {adopted} |
| ❌ Skipped | {skipped} |
| 🔧 Realigned | {realigned} |

---

## Notes

{notes if notes else "No additional notes."}

---

## Analysis Method

This report was generated via `scripts/workflow/generate_gmp_report.py` after inline PR analysis.

See ADR-0059 for report generation policy.

---

## Report Metadata

- **GMP Number:** {gmp_number}
- **PR Number:** {pr_number}
- **Generated By:** generate_gmp_report.py
"""
    
    return filename, content


def main():
    parser = argparse.ArgumentParser(
        description="Generate GMP report for PR analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Basic report
    python3 scripts/workflow/generate_gmp_report.py --pr 51 --title "Fix Bug" --adopted 3
    
    # Full report
    python3 scripts/workflow/generate_gmp_report.py \\
        --pr 51 \\
        --title "Spring Cleaning TODO Tracking" \\
        --adopted 11 --skipped 0 --realigned 0 \\
        --tier RUNTIME \\
        --notes "23 TODOs tagged with GMP-100-122"
        """,
    )
    
    parser.add_argument("--pr", type=int, required=True, help="PR number")
    parser.add_argument("--title", type=str, required=True, help="PR title")
    parser.add_argument("--adopted", type=int, default=0, help="Files adopted")
    parser.add_argument("--skipped", type=int, default=0, help="Files skipped")
    parser.add_argument("--realigned", type=int, default=0, help="Files realigned")
    parser.add_argument("--tier", type=str, default="RUNTIME", 
                       choices=["KERNEL", "RUNTIME", "INFRA", "UX"],
                       help="Tier classification")
    parser.add_argument("--notes", type=str, default="", help="Additional notes")
    parser.add_argument("--author", type=str, default="cryptoxdog", help="PR author")
    parser.add_argument("--files", type=int, default=None, help="Total files changed")
    parser.add_argument("--dry-run", action="store_true", help="Print without saving")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    
    args = parser.parse_args()
    
    filename, content = generate_report(
        pr_number=args.pr,
        title=args.title,
        adopted=args.adopted,
        skipped=args.skipped,
        realigned=args.realigned,
        tier=args.tier,
        notes=args.notes,
        author=args.author,
        files_changed=args.files,
    )
    
    reports_dir = Path(__file__).parent.parent.parent / "reports"
    filepath = reports_dir / filename
    
    if args.json:
        output = {
            "filename": filename,
            "filepath": str(filepath),
            "gmp_number": int(re.search(r"GMP-Report-(\d+)-", filename).group(1)),
            "pr_number": args.pr,
        }
        print(json.dumps(output, indent=2))
        return
    
    if args.dry_run:
        print(f"Would create: {filepath}\n")
        print("--- Content ---")
        print(content)
        return
    
    # Save report
    filepath.write_text(content)
    print(f"✅ Report saved: {filepath}")
    print(f"   GMP Number: {re.search(r'GMP-Report-([0-9]+)-', filename).group(1)}")


if __name__ == "__main__":
    main()
