#!/usr/bin/env python3
"""
generate_delete_sql.py - Generate SQL to Delete Trash Embeddings
================================================================

Finds trash embeddings via API and generates SQL DELETE statement.

Usage:
    python3 scripts/generate_delete_sql.py > delete_trash.sql
    psql -d l9 -f delete_trash.sql
"""

# ============================================================================
__dora_meta__ = {
    "component_name": "Generate SQL to Delete Trash Embeddings",
    "module_version": "1.0.0",
    "created_by": "Igor Beylin",
    "created_at": "2026-01-11T18:13:39Z",
    "updated_at": "2026-01-10T17:48:00Z",
    "layer": "operations",
    "domain": "memory_substrate",
    "module_name": "generate_delete_sql",
    "type": "service",
    "status": "active",
    "integrates_with": {
        "api_endpoints": [],
        "datasources": ["HTTP API"],
        "memory_layers": ["semantic_memory"],
        "imported_by": [],
    },
}
# ============================================================================

import asyncio
import os
import sys
from pathlib import Path

import httpx
import structlog
from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

load_dotenv()

logger = structlog.get_logger(__name__)

VPS_URL = os.getenv("VPS_MEMORY_URL", "https://157.180.73.53:9001")
API_KEY = os.getenv("L9_EXECUTOR_API_KEY")

ERROR_PATTERNS = [
    "Sorry, I encountered a temporary error. Please try again.",
    "Sorry, I encountered an error processing your command.",
    "No response generated.",
    "This message has already been processed.",
]


def is_trash(payload: dict) -> bool:
    """Check if payload contains trash content."""
    text = (
        payload.get("_text")
        or payload.get("text")
        or payload.get("content")
        or str(payload.get("payload", ""))
    )

    if not isinstance(text, str):
        text = str(text)

    text = text.strip()

    # Check error patterns
    for pattern in ERROR_PATTERNS:
        if pattern in text:
            return True

    # Very short
    return len(text) < 20


async def find_trash_ids() -> list:
    """Find trash embedding IDs via API."""
    if not API_KEY:
        logger.error("L9_EXECUTOR_API_KEY not set")
        return []

    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
    }

    trash_ids = []
    search_queries = [
        "Sorry, I encountered a temporary error",
        "Sorry, I encountered an error",
        "No response generated",
    ]

    async with httpx.AsyncClient(verify=False, timeout=60.0) as client:
        for query in search_queries:
            try:
                response = await client.post(
                    f"{VPS_URL}/api/v1/memory/semantic/search",
                    headers=headers,
                    json={
                        "query": query,
                        "top_k": 100,
                        "min_score": 0.1,
                    },
                )

                if response.status_code == 200:
                    result = response.json()
                    for hit in result.get("hits", []):
                        payload = hit.get("payload", {})
                        embedding_id = hit.get("embedding_id")

                        if embedding_id and is_trash(payload):
                            if embedding_id not in trash_ids:
                                trash_ids.append(embedding_id)

            except Exception as e:
                logger.error(f"Search failed: {e}")

    return trash_ids


async def main():
    """Generate SQL DELETE statement."""
    logger.error("-- sql to delete trash embeddings containing error messages")
    logger.info("-- generated by generate_delete_sql.py")
    logger.info("-- run with: psql -d l9 -f delete_trash.sql")
    logger.info("output", value=)
    logger.info("begin;")
    logger.info("output", value=)

    trash_ids = await find_trash_ids()

    if not trash_ids:
        logger.info("-- no trash embeddings found")
        logger.info("commit;")
        return

    logger.info("-- found {len(trash_ids)} trash embeddings to delete")
    logger.info("output", value=)

    # Generate DELETE statement
    logger.info("delete from semantic_memory")
    logger.info("where embedding_id in (")

    for i, eid in enumerate(trash_ids):
        comma = "," if i < len(trash_ids) - 1 else ""
        logger.info("    'eid'comma", eid=eid, comma=comma)

    logger.info(");")
    logger.info("output", value=)
    logger.info("-- deletes {len(trash_ids)} embeddings")
    logger.info("commit;")


if __name__ == "__main__":
    asyncio.run(main())

# ============================================================================
# DORA FOOTER META - AUTO-GENERATED - DO NOT EDIT MANUALLY
# ============================================================================
__dora_footer__ = {
    "component_id": "SCR-OPER-001",
    "governance_level": "critical",
    "compliance_required": True,
    "audit_trail": True,
    "dependencies": [],
    "tags": [
        "api",
        "async",
        "auth",
        "filesystem",
        "http-client",
        "logging",
        "memory-substrate",
        "messaging",
        "operations",
        "service",
    ],
    "keywords": ["delete", "embeddings", "find", "generate", "ids", "sql", "trash"],
    "business_value": "Utility module for generate delete sql",
    "last_modified": "2026-01-10T17:48:00Z",
    "modified_by": "L9_Codegen_Engine",
    "change_summary": "Initial generation with DORA compliance",
}
# ============================================================================
# L9 DORA BLOCK - AUTO-UPDATED - DO NOT EDIT
# Runtime execution trace - updated automatically on every execution
# ============================================================================
__l9_trace__ = {
    "trace_id": "",
    "task": "",
    "timestamp": "",
    "patterns_used": [],
    "graph": {"nodes": [], "edges": []},
    "inputs": {},
    "outputs": {},
    "metrics": {"confidence": "", "errors_detected": [], "stability_score": ""},
}
# ============================================================================
# END L9 DORA BLOCK
# ============================================================================
