#!/usr/bin/env python3
"""
generate_delete_sql.py - Generate SQL to Delete Trash Embeddings
================================================================

Finds trash embeddings via API and generates SQL DELETE statement.

Usage:
    python3 scripts/generate_delete_sql.py > delete_trash.sql
    psql -d l9 -f delete_trash.sql
"""

import os
import sys
import asyncio
import httpx
import structlog
from dotenv import load_dotenv
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

load_dotenv()

logger = structlog.get_logger(__name__)

VPS_URL = os.getenv("VPS_MEMORY_URL", "https://157.180.73.53:9001")
API_KEY = os.getenv("L9_EXECUTOR_API_KEY")

ERROR_PATTERNS = [
    "Sorry, I encountered a temporary error. Please try again.",
    "Sorry, I encountered an error processing your command.",
    "No response generated.",
    "This message has already been processed.",
]


def is_trash(payload: dict) -> bool:
    """Check if payload contains trash content."""
    text = (
        payload.get("_text") or
        payload.get("text") or
        payload.get("content") or
        str(payload.get("payload", ""))
    )
    
    if not isinstance(text, str):
        text = str(text)
    
    text = text.strip()
    
    # Check error patterns
    for pattern in ERROR_PATTERNS:
        if pattern in text:
            return True
    
    # Very short
    if len(text) < 20:
        return True
    
    return False


async def find_trash_ids() -> list:
    """Find trash embedding IDs via API."""
    if not API_KEY:
        logger.error("L9_EXECUTOR_API_KEY not set")
        return []
    
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
    }
    
    trash_ids = []
    search_queries = [
        "Sorry, I encountered a temporary error",
        "Sorry, I encountered an error",
        "No response generated",
    ]
    
    async with httpx.AsyncClient(verify=False, timeout=60.0) as client:
        for query in search_queries:
            try:
                response = await client.post(
                    f"{VPS_URL}/api/v1/memory/semantic/search",
                    headers=headers,
                    json={
                        "query": query,
                        "top_k": 100,
                        "min_score": 0.1,
                    },
                )
                
                if response.status_code == 200:
                    result = response.json()
                    for hit in result.get("hits", []):
                        payload = hit.get("payload", {})
                        embedding_id = hit.get("embedding_id")
                        
                        if embedding_id and is_trash(payload):
                            if embedding_id not in trash_ids:
                                trash_ids.append(embedding_id)
            
            except Exception as e:
                logger.error(f"Search failed: {e}")
    
    return trash_ids


async def main():
    """Generate SQL DELETE statement."""
    print("-- SQL to delete trash embeddings containing error messages")
    print("-- Generated by generate_delete_sql.py")
    print("-- Run with: psql -d l9 -f delete_trash.sql")
    print()
    print("BEGIN;")
    print()
    
    trash_ids = await find_trash_ids()
    
    if not trash_ids:
        print("-- No trash embeddings found")
        print("COMMIT;")
        return
    
    print(f"-- Found {len(trash_ids)} trash embeddings to delete")
    print()
    
    # Generate DELETE statement
    print("DELETE FROM semantic_memory")
    print("WHERE embedding_id IN (")
    
    for i, eid in enumerate(trash_ids):
        comma = "," if i < len(trash_ids) - 1 else ""
        print(f"    '{eid}'{comma}")
    
    print(");")
    print()
    print(f"-- Deletes {len(trash_ids)} embeddings")
    print("COMMIT;")


if __name__ == "__main__":
    asyncio.run(main())

