"""
L9 Core Schemas Module

Generated by L9_MASTER_SCHEMA_EXTRACTOR v3.0
Aligned with Memory.yaml v1.0.1

Source schemas:
  - Memory.yaml v1.0.1 (PacketEnvelope, aligned_with_repo)
  - research_factory_schema.yaml (5-pass pipeline)
  - capabilities.py (Security - Agent Capabilities)
  - event_stream.py (Security - Event Stream Types)

All models are Pydantic v2 compliant with strict validation.
"""

# ============================================================================
__dora_meta__ = {
    "component_name": "  Init  ",
    "module_version": "1.0.0",
    "created_by": "Igor Beylin",
    "created_at": "2025-12-09T01:02:49Z",
    "updated_at": "2026-01-31T22:21:47Z",
    "layer": "foundation",
    "domain": "core",
    "module_name": "__init__",
    "type": "schema",
    "status": "active",
    "integrates_with": {
        "api_endpoints": [],
        "datasources": [],
        "memory_layers": ["semantic_memory", "working_memory"],
        "imported_by": [],
    },
}
# ============================================================================

# L9 Unified Base Model (DORA compliance, content hashing, streaming)
from core.models.l9_base_model import L9BaseModel

# Security Schemas
from core.schemas.capabilities import (
    DEFAULT_ARCHITECT_CAPABILITIES,
    DEFAULT_CODER_CAPABILITIES,
    DEFAULT_READER_CAPABILITIES,
    AgentCapabilities,
    Capability,
    ToolName,
)
from core.schemas.event_stream import (
    AgentHandshake,
    CapabilityViolation,
    HandshakeResponse,
    HandshakeStatus,
    SecurityEvent,
    SecurityEventType,
    create_handshake_event,
    create_violation_event,
)
from core.schemas.packet_envelope_v2 import (  # Core Packet Models; Packet Components; Enums; Search Models; Schema Version Constants
    SCHEMA_VERSION,
    SUPPORTED_VERSIONS,
    VALID_DERIVE_TYPES,
    DerivationType,
    DeriveType,
    PacketConfidence,
    PacketEnvelope,
    PacketEnvelopeIn,
    PacketKind,
    PacketLineage,
    PacketMetadata,
    PacketProvenance,
    PacketWriteResult,
    SemanticHit,
    SemanticSearchRequest,
    SemanticSearchResult,
)
from core.schemas.research_factory_models import (
    IntegrationResult,
    ParsedObject,
    Query,
    QueryPlan,
    ResearchJobSpec,
    ResearchMetrics,
    RetrievalBatch,
    Superprompt,
    ValidationStatus,
)
from core.schemas.research_factory_nodes import (
    pass_1_plan_queries,
    pass_2_build_superprompts,
    pass_3_execute_retrieval,
    pass_4_extract_results,
    pass_5_integrate_results,
)
from core.schemas.research_factory_state import PassStatus, ResearchState

# Task Types (Phase 2.5)
from core.schemas.tasks import (
    AgentTask,
    TaskBatch,
    TaskEnvelope,
    TaskGraph,
    TaskKind,
    TaskResult,
    TaskStatus,
)

# Role-Based Tool Capabilities (Enhancement from GMP MCP-Tools)
from core.schemas.tool_role_capabilities import (
    ToolCapabilities,
    ToolCapability,
    filter_tools_by_capabilities,
)

# WebSocket Event Stream
from core.schemas.ws_event_stream import (
    AgentHeartbeat,
    ErrorEvent,
    EventMessage,
    EventType,
)

__all__ = [
    "DEFAULT_ARCHITECT_CAPABILITIES",
    "DEFAULT_CODER_CAPABILITIES",
    "DEFAULT_READER_CAPABILITIES",
    # Schema Version Constants
    "SCHEMA_VERSION",
    "SUPPORTED_VERSIONS",
    "VALID_DERIVE_TYPES",
    "AgentCapabilities",
    "AgentHandshake",
    "AgentHeartbeat",
    "AgentTask",
    "Capability",
    "CapabilityViolation",
    "DerivationType",
    "DeriveType",
    "ErrorEvent",
    "EventMessage",
    # WebSocket Event Stream
    "EventType",
    "HandshakeResponse",
    # Security - Event Stream
    "HandshakeStatus",
    "IntegrationResult",
    # L9 Unified Base Model
    "L9BaseModel",
    "PacketConfidence",
    # Packet Envelope (Memory.yaml v1.0.1) - CANONICAL IMPORTS
    "PacketEnvelope",
    "PacketEnvelopeIn",
    # Enums
    "PacketKind",
    "PacketLineage",
    "PacketMetadata",
    "PacketProvenance",
    "PacketWriteResult",
    "ParsedObject",
    "PassStatus",
    "Query",
    "QueryPlan",
    # Research Factory Models
    "ResearchJobSpec",
    "ResearchMetrics",
    # Research Factory State
    "ResearchState",
    "RetrievalBatch",
    "SecurityEvent",
    "SecurityEventType",
    "SemanticHit",
    # Search Models
    "SemanticSearchRequest",
    "SemanticSearchResult",
    "Superprompt",
    "TaskBatch",
    "TaskEnvelope",
    "TaskGraph",
    "TaskKind",
    "TaskResult",
    # Task Types (Phase 2.5)
    "TaskStatus",
    # Security - Capabilities
    "ToolName",
    # Role-Based Tool Capabilities (GMP MCP-Tools)
    "ToolCapabilities",
    "ToolCapability",
    "filter_tools_by_capabilities",
    "ValidationStatus",
    "create_handshake_event",
    "create_violation_event",
    # Research Factory Nodes
    "pass_1_plan_queries",
    "pass_2_build_superprompts",
    "pass_3_execute_retrieval",
    "pass_4_extract_results",
    "pass_5_integrate_results",
]
# ============================================================================
# DORA FOOTER META - AUTO-GENERATED - DO NOT EDIT MANUALLY
# ============================================================================
__dora_footer__ = {
    "component_id": "COR-FOUN-144",
    "governance_level": "critical",
    "compliance_required": True,
    "audit_trail": True,
    "dependencies": [
        "core.models.l9_base_model",
        "core.schemas.capabilities",
        "core.schemas.event_stream",
        "core.schemas.packet_envelope_v2",
        "core.schemas.research_factory_models",
    ],
    "tags": [
        "batch-processing",
        "core",
        "event-driven",
        "foundation",
        "messaging",
        "metrics",
        "pydantic",
        "realtime",
        "schema",
        "security",
    ],
    "keywords": [
        "agent",
        "capabilities",
        "memory",
        "module",
        "schemas",
        "security",
        "yaml",
    ],
    "business_value": "Utility module for   init  ",
    "last_modified": "2026-01-31T22:21:47Z",
    "modified_by": "L9_Codegen_Engine",
    "change_summary": "Initial generation with DORA compliance",
}
# ============================================================================
# L9 DORA BLOCK - AUTO-UPDATED - DO NOT EDIT
# Runtime execution trace - updated automatically on every execution
# ============================================================================
__l9_trace__ = {
    "trace_id": "",
    "task": "",
    "timestamp": "",
    "patterns_used": [],
    "graph": {"nodes": [], "edges": []},
    "inputs": {},
    "outputs": {},
    "metrics": {"confidence": "", "errors_detected": [], "stability_score": ""},
}
# ============================================================================
# END L9 DORA BLOCK
# ============================================================================
