"""
L9 Module Compiler v2.0.0
=========================

Deterministic compiler that transforms Module-Spec v2.6 into production-ready
L9-integrated Python modules.

**L9 Alignment Features**:
- Inherits from BaseAgent (not standalone orchestrator)
- Returns PacketEnvelope v2.0.0 (not dict)
- Uses absolute L9 imports
- Includes @rate_limit decorators
- Includes @async_retry decorators
- Generates tool YAML configs for Neo4j registry

Version: 2.0.0 (L9-Aligned)
"""

# ============================================================================
__dora_meta__ = {
    "component_name": "Module Compiler V2",
    "module_version": "2.0.0",
    "created_by": "CodeGenAgent",
    "created_at": "2025-12-31T20:00:00Z",
    "updated_at": "2025-12-31T20:00:00Z",
    "layer": "intelligence",
    "domain": "codegen",
    "module_name": "module_compiler_v2",
    "type": "class",
    "status": "active",
    "integrates_with": {
        "api_endpoints": [],
        "datasources": [],
        "memory_layers": ["working_memory"],
        "imported_by": ["core.codegen.gatekeeper.codegen_gatekeeper"],
    },
}
# ============================================================================

import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

import structlog
from jinja2 import Template

logger = structlog.get_logger(__name__)


# =============================================================================
# Templates (L9-Aligned)
# =============================================================================

# Template 1: Agent Core (inherits from BaseAgent)
TEMPLATE_AGENT_CORE = """\"\"\"
{{metadata.name}} - L9 Agent
{{description_line}}

Generated by: CodeGenAgent v2.0.0
Generated at: {{timestamp}}
Module ID: {{module_id}}
\"\"\"

# ============================================================================
__dora_meta__ = {
    "component_name": "{{metadata.name}}",
    "module_version": "{{metadata.version}}",
    "created_by": "CodeGenAgent",
    "created_at": "{{timestamp}}",
    "updated_at": "{{timestamp}}",
    "layer": "intelligence",
    "domain": "{{metadata.domain | default('agents')}}",
    "module_name": "{{module_id}}_agent",
    "type": "class",
    "status": "active",
    "integrates_with": {
        "api_endpoints": [],
        "datasources": {{datasources | tojson}},
        "memory_layers": ["working_memory", "episodic_memory"],
        "imported_by": [],
    },
}
# ============================================================================

from __future__ import annotations

import structlog
from typing import Any, Optional
from uuid import uuid4

# L9 Core Imports (absolute paths)
from agents.base_agent import BaseAgent, AgentConfig, AgentResponse, AgentRole
from core.schemas import PacketEnvelope, PacketMetadata, PacketProvenance, PacketKind
from core.governance.rate_limit_policy import rate_limit
from core.resilience.retry import async_retry, AsyncRetryConfig
from core.decorators import must_stay_async

{% if has_memory %}
from clients.memory_client import MemoryClient
{% endif %}

{% if has_tools %}
from core.tools.registry import get_tool
{% endif %}

from .config import {{class_name}}Config
from .models import {{class_name}}Request

logger = structlog.get_logger(__name__)


class {{class_name}}Agent(BaseAgent):
    \"\"\"
    {{metadata.name}} - L9 Agent
    
    {{metadata.description}}
    
    **Agent Role**: {{agent_role}}
    **Tier**: {{tier}}
    **Escalation Path**: {{escalation_path}}
    \"\"\"
    
    agent_role = AgentRole.{{agent_role_enum}}
    agent_name = "{{module_id}}_agent"
    
    def __init__(
        self,
        agent_id: Optional[str] = None,
        config: Optional[AgentConfig] = None,
    ):
        \"\"\"
        Initialize {{metadata.name}} agent.
        
        Args:
            agent_id: Unique agent identifier (auto-generated if not provided)
            config: Agent configuration (uses defaults if not provided)
        \"\"\"
        super().__init__(agent_id, config)
        self.module_config = {{class_name}}Config()
        {% if has_memory %}
        self.memory = MemoryClient()
        {% endif %}
        
        logger.info(
            "{{metadata.name}} initialized",
            agent_id=self.agent_id,
            tier={{tier}},
            escalation_path="{{escalation_path}}"
        )
    
    def get_system_prompt(self) -> str:
        \"\"\"
        Get the agent's system prompt.
        
        Returns:
            System prompt string
        \"\"\"
        return f\"\"\"You are {{metadata.name}}.

Role: {{metadata.role}}
Description: {{metadata.description}}

You are a Tier {{tier}} agent in the L9 AIOS hierarchy.
Escalation path: {{escalation_path}}

Your responsibilities:
{{responsibilities}}

Always respond with structured, actionable outputs.
\"\"\"
    
    @must_stay_async("callers use await")
    async def run(
        self,
        task: dict[str, Any],
        context: Optional[dict[str, Any]] = None
    ) -> AgentResponse:
        \"\"\"
        Execute the agent's primary function.
        
        Args:
            task: Task specification with 'data' field
            context: Optional execution context
        
        Returns:
            AgentResponse with PacketEnvelope result
        \"\"\"
        logger.info(
            "{{metadata.name}} starting task",
            agent_id=self.agent_id,
            task_keys=list(task.keys())
        )
        
        try:
            # Parse request
            request = {{class_name}}Request(**task)
            
            # Execute logic
            result = await self._execute_logic(request, context)
            
            # Create PacketEnvelope response
            packet = PacketEnvelope(
                packet_type="{{packet_type}}",
                payload=result,
                metadata=PacketMetadata(
                    agent=self.agent_name,
                    schema_version="2.0.0",
                    domain="{{metadata.domain | default('l9')}}"
                ),
                provenance=PacketProvenance(
                    source_agent=self.agent_id,
                    source="{{module_id}}_agent",
                    tool="{{module_id}}"
                )
            )
            
            {% if has_memory %}
            # Write to memory substrate
            await self.memory.write_packet(packet)
            {% endif %}
            
            logger.info(
                "{{metadata.name}} task completed",
                agent_id=self.agent_id,
                packet_id=str(packet.packet_id),
                success=True
            )
            
            return AgentResponse(
                agent_id=self.agent_id,
                content=str(result),
                structured_output=result,
                success=True
            )
            
        except Exception as e:
            logger.error(
                "{{metadata.name}} task failed",
                agent_id=self.agent_id,
                error=str(e),
                exc_info=True
            )
            
            # Return error response
            return AgentResponse(
                agent_id=self.agent_id,
                content=f"Error: {str(e)}",
                success=False,
                error=str(e)
            )
    
    @rate_limit("agent.{{module_id}}")
    @async_retry(AsyncRetryConfig(max_retries=3, backoff_factor=2.0))
    async def _execute_logic(
        self,
        request: {{class_name}}Request,
        context: Optional[dict[str, Any]] = None
    ) -> dict[str, Any]:
        \"\"\"
        Execute the core agent logic.
        
        Args:
            request: Validated request model
            context: Optional execution context
        
        Returns:
            Result dictionary
        \"\"\"
        # TODO: Implement agent-specific logic
        
        {% if has_llm %}
        # Example: Call LLM
        from agents.base_agent import AgentMessage
        
        messages = [
            AgentMessage(role="user", content=request.data.get("query", ""))
        ]
        
        llm_response = await self.call_llm(messages)
        
        return {
            "result": llm_response.content,
            "tokens_used": llm_response.tokens_used
        }
        {% else %}
        # Example: Process request data
        return {
            "result": "processed",
            "data": request.data
        }
        {% endif %}
"""

# Template 2: Config (Pydantic Settings)
TEMPLATE_CONFIG = """\"\"\"
{{metadata.name}} - Configuration
\"\"\"

import os
from pydantic_settings import BaseSettings
from typing import Optional


class {{class_name}}Config(BaseSettings):
    \"\"\"Configuration for {{metadata.name}}\"\"\"
    
    # Module settings
    module_id: str = "{{module_id}}"
    module_version: str = "{{metadata.version}}"
    
    # Environment-specific settings
    {{config_fields}}
    
    class Config:
        env_prefix = "{{env_prefix}}_"
        case_sensitive = False
"""

# Template 3: Models (Pydantic Request/Response)
TEMPLATE_MODELS = """\"\"\"
{{metadata.name}} - Data Models
\"\"\"

from pydantic import BaseModel, Field
from typing import Any, Optional
from datetime import datetime
from uuid import UUID, uuid4


class {{class_name}}Request(BaseModel):
    \"\"\"Request model for {{metadata.name}}\"\"\"
    
    data: dict[str, Any] = Field(..., description="Request data payload")
    metadata: Optional[dict[str, Any]] = Field(None, description="Optional metadata")
    
    class Config:
        frozen = False
"""

# Template 4: Tool YAML Config
TEMPLATE_TOOL_YAML = """# Tool Configuration for {{metadata.name}}
# Generated by: CodeGenAgent v2.0.0
# Module ID: {{module_id}}

tool_id: "{{module_id}}_tool"
name: "{{metadata.name}}"
description: "{{metadata.description}}"
category: "{{tool_category}}"
scope: "{{tool_scope}}"
risk_level: "{{risk_level}}"

# Function binding
function:
  module: "{{module_path}}"
  class: "{{class_name}}Agent"
  method: "run"

# Input schema
input_schema:
  type: "object"
  properties:
    data:
      type: "object"
      description: "Request data payload"
  required: ["data"]

# Output schema
output_schema:
  type: "object"
  properties:
    result:
      type: "object"
      description: "Agent execution result"

# Governance
governance:
  requires_approval: {{requires_approval}}
  escalation_path: "{{escalation_path}}"
  tier: {{tier}}

# Rate limiting
rate_limit:
  requests_per_minute: 60
  burst_size: 10

# Dependencies
dependencies:
  kernels: {{kernel_dependencies | tojson}}
  services: {{service_dependencies | tojson}}
"""

# Template 5: Tests
TEMPLATE_TESTS = """\"\"\"
Tests for {{metadata.name}}
\"\"\"

import pytest
from unittest.mock import AsyncMock, MagicMock

from agents.base_agent import AgentResponse
from {{module_path}}.core import {{class_name}}Agent
from {{module_path}}.models import {{class_name}}Request


@pytest.mark.asyncio
async def test_{{module_id}}_agent_initialization():
    \"\"\"Test agent initialization\"\"\"
    agent = {{class_name}}Agent()
    
    assert agent.agent_name == "{{module_id}}_agent"
    assert agent.agent_id is not None


@pytest.mark.asyncio
async def test_{{module_id}}_agent_run_success():
    \"\"\"Test successful agent execution\"\"\"
    agent = {{class_name}}Agent()
    
    task = {
        "data": {"test": "value"}
    }
    
    response = await agent.run(task)
    
    assert isinstance(response, AgentResponse)
    assert response.success is True
    assert response.agent_id == agent.agent_id


@pytest.mark.asyncio
async def test_{{module_id}}_agent_run_error():
    \"\"\"Test agent error handling\"\"\"
    agent = {{class_name}}Agent()
    
    # Invalid task
    task = {}
    
    response = await agent.run(task)
    
    assert isinstance(response, AgentResponse)
    assert response.success is False
    assert response.error is not None
"""


# =============================================================================
# Module Compiler
# =============================================================================


@dataclass
class CompilerOutput:
    """Output from module compilation"""

    files_generated: list[str]
    output_dir: Path
    module_id: str
    confidence: float


class ModuleCompilerV2:
    """
    L9-Aligned Module Compiler v2.0.0

    Transforms Module-Spec v2.6 into production-ready L9 agents.
    """

    def __init__(self):
        self.logger = logger

    async def compile(
        self, spec: dict[str, Any], output_dir: str | Path
    ) -> CompilerOutput:
        """
        Compile Module-Spec v2.6 into L9-integrated agent.

        Args:
            spec: Normalized Module-Spec v2.6
            output_dir: Output directory path

        Returns:
            CompilerOutput with file list and metadata
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        metadata = spec.get("metadata", {})
        module_id = metadata.get("module_id", "unknown_module")

        self.logger.info(
            "Starting module compilation",
            module_id=module_id,
            output_dir=str(output_path),
        )

        files_generated = []

        # Generate core agent file
        core_file = await self._generate_agent_core(spec, output_path)
        files_generated.append(core_file)

        # Generate config file
        config_file = await self._generate_config(spec, output_path)
        files_generated.append(config_file)

        # Generate models file
        models_file = await self._generate_models(spec, output_path)
        files_generated.append(models_file)

        # Generate tool YAML config
        tool_yaml = await self._generate_tool_yaml(spec, output_path)
        files_generated.append(tool_yaml)

        # Generate tests
        test_file = await self._generate_tests(spec, output_path)
        files_generated.append(test_file)

        # Generate __init__.py
        init_file = await self._generate_init(spec, output_path)
        files_generated.append(init_file)

        # Generate README
        readme_file = await self._generate_readme(spec, output_path)
        files_generated.append(readme_file)

        self.logger.info(
            "Module compilation complete",
            module_id=module_id,
            files_generated=len(files_generated),
        )

        return CompilerOutput(
            files_generated=files_generated,
            output_dir=output_path,
            module_id=module_id,
            confidence=95.0,
        )

    async def _generate_agent_core(self, spec: dict, output_dir: Path) -> str:
        """Generate core agent file (inherits from BaseAgent)"""
        metadata = spec.get("metadata", {})
        module_id = metadata.get("module_id", "unknown")
        class_name = self._to_class_name(module_id)

        # Determine agent role
        agent_role = spec.get("system", {}).get("role", "General Agent")
        agent_role_enum = self._map_agent_role(agent_role)

        # Determine tier and escalation
        tier = spec.get("governance", {}).get("tier", 2)
        escalation_path = spec.get("governance", {}).get("escalation_path", "Igor")

        # Check for dependencies
        integration = spec.get("integration", {})
        depends_on = integration.get("depends_on", [])
        has_memory = "memory.service" in depends_on
        has_tools = "tool_registry" in depends_on
        has_llm = "llm" in depends_on or "openai" in depends_on

        # Datasources
        datasources = []
        if has_memory:
            datasources.extend(["PostgreSQL", "Redis"])
        if has_llm:
            datasources.append("OpenAI API")

        # Responsibilities
        responsibilities = metadata.get("description", "Execute assigned tasks")

        template = Template(TEMPLATE_AGENT_CORE)
        content = template.render(
            metadata=metadata,
            module_id=module_id,
            class_name=class_name,
            agent_role=agent_role,
            agent_role_enum=agent_role_enum,
            tier=tier,
            escalation_path=escalation_path,
            has_memory=has_memory,
            has_tools=has_tools,
            has_llm=has_llm,
            datasources=datasources,
            responsibilities=responsibilities,
            packet_type=f"agent.{module_id}.result",
            description_line="=" * len(metadata.get("name", "")),
            timestamp=datetime.utcnow().isoformat() + "Z",
        )

        file_path = output_dir / "core.py"
        file_path.write_text(content)

        return str(file_path)

    async def _generate_config(self, spec: dict, output_dir: Path) -> str:
        """Generate config file"""
        metadata = spec.get("metadata", {})
        module_id = metadata.get("module_id", "unknown")
        class_name = self._to_class_name(module_id)
        env_prefix = module_id.upper()

        # Generate config fields from spec
        config_fields = []
        external_services = spec.get("dependency_contract", {}).get(
            "external_services", []
        )
        for service in external_services:
            service_name = service.get("name", "").upper()
            config_fields.append(f"    {service_name}_API_KEY: Optional[str] = None")

        if not config_fields:
            config_fields.append("    # Add configuration fields here")

        template = Template(TEMPLATE_CONFIG)
        content = template.render(
            metadata=metadata,
            module_id=module_id,
            class_name=class_name,
            env_prefix=env_prefix,
            config_fields="\n".join(config_fields),
        )

        file_path = output_dir / "config.py"
        file_path.write_text(content)

        return str(file_path)

    async def _generate_models(self, spec: dict, output_dir: Path) -> str:
        """Generate models file"""
        metadata = spec.get("metadata", {})
        module_id = metadata.get("module_id", "unknown")
        class_name = self._to_class_name(module_id)

        template = Template(TEMPLATE_MODELS)
        content = template.render(
            metadata=metadata, module_id=module_id, class_name=class_name
        )

        file_path = output_dir / "models.py"
        file_path.write_text(content)

        return str(file_path)

    async def _generate_tool_yaml(self, spec: dict, output_dir: Path) -> str:
        """Generate tool YAML config for Neo4j registry"""
        metadata = spec.get("metadata", {})
        module_id = metadata.get("module_id", "unknown")
        class_name = self._to_class_name(module_id)

        # Determine tool properties
        tier = spec.get("governance", {}).get("tier", 2)
        escalation_path = spec.get("governance", {}).get("escalation_path", "Igor")

        tool_category = "general"
        tool_scope = "internal"
        risk_level = "low"
        requires_approval = "false"

        if tier >= 3:
            risk_level = "high"
            requires_approval = "true"

        # Dependencies
        integration = spec.get("integration", {})
        depends_on = integration.get("depends_on", [])

        kernel_dependencies = []
        service_dependencies = []

        for dep in depends_on:
            if "kernel" in dep:
                kernel_dependencies.append(dep)
            else:
                service_dependencies.append(dep)

        if not kernel_dependencies:
            kernel_dependencies = ["01-master-kernel.yaml"]

        template = Template(TEMPLATE_TOOL_YAML)
        content = template.render(
            metadata=metadata,
            module_id=module_id,
            class_name=class_name,
            module_path=f"agents.{module_id}",
            tool_category=tool_category,
            tool_scope=tool_scope,
            risk_level=risk_level,
            requires_approval=requires_approval,
            escalation_path=escalation_path,
            tier=tier,
            kernel_dependencies=kernel_dependencies,
            service_dependencies=service_dependencies,
        )

        file_path = output_dir / f"{module_id}_tool.yaml"
        file_path.write_text(content)

        return str(file_path)

    async def _generate_tests(self, spec: dict, output_dir: Path) -> str:
        """Generate test file"""
        metadata = spec.get("metadata", {})
        module_id = metadata.get("module_id", "unknown")
        class_name = self._to_class_name(module_id)
        module_path = f"agents.{module_id}"

        template = Template(TEMPLATE_TESTS)
        content = template.render(
            metadata=metadata,
            module_id=module_id,
            class_name=class_name,
            module_path=module_path,
        )

        tests_dir = output_dir / "tests"
        tests_dir.mkdir(exist_ok=True)

        file_path = tests_dir / f"test_{module_id}_agent.py"
        file_path.write_text(content)

        return str(file_path)

    async def _generate_init(self, spec: dict, output_dir: Path) -> str:
        """Generate __init__.py"""
        metadata = spec.get("metadata", {})
        module_id = metadata.get("module_id", "unknown")
        class_name = self._to_class_name(module_id)

        content = f'''"""
{metadata.get("name", "Module")} - L9 Agent
"""

from .core import {class_name}Agent
from .models import {class_name}Request
from .config import {class_name}Config

__all__ = ["{class_name}Agent", "{class_name}Request", "{class_name}Config"]
'''

        file_path = output_dir / "__init__.py"
        file_path.write_text(content)

        return str(file_path)

    async def _generate_readme(self, spec: dict, output_dir: Path) -> str:
        """Generate README"""
        metadata = spec.get("metadata", {})
        module_id = metadata.get("module_id", "unknown")
        class_name = self._to_class_name(module_id)

        content = f"""# {metadata.get("name", "Module")}

{metadata.get("description", "No description provided")}

## Generated by CodeGenAgent v2.0.0

**Module ID**: `{module_id}`  
**Version**: `{metadata.get("version", "1.0.0")}`  
**Tier**: `{spec.get("governance", {}).get("tier", 2)}`  
**Escalation Path**: `{spec.get("governance", {}).get("escalation_path", "Igor")}`

## Usage

```python
from agents.{module_id} import {class_name}Agent

# Initialize agent
agent = {class_name}Agent()

# Run task
response = await agent.run(task={{
    "data": {{"key": "value"}}
}})

print(response.content)
```

## Integration

This agent is fully integrated with L9 AIOS:
- ✅ Inherits from `BaseAgent`
- ✅ Returns `PacketEnvelope` responses
- ✅ Uses L9 rate limiting
- ✅ Uses L9 retry logic
- ✅ Registered in tool registry

## Testing

```bash
pytest tests/test_{module_id}_agent.py -v
```
"""

        file_path = output_dir / "README.md"
        file_path.write_text(content)

        return str(file_path)

    def _to_class_name(self, module_id: str) -> str:
        """Convert module_id to PascalCase class name"""
        parts = module_id.split("_")
        return "".join(word.capitalize() for word in parts)

    def _map_agent_role(self, role_str: str) -> str:
        """Map role string to AgentRole enum"""
        role_lower = role_str.lower()

        if "architect" in role_lower:
            return "ARCHITECT_PRIMARY"
        elif "coder" in role_lower or "code" in role_lower:
            return "CODER_PRIMARY"
        elif "qa" in role_lower or "quality" in role_lower:
            return "QA"
        else:
            return "REFLECTION"


# ============================================================================
# DORA FOOTER META - AUTO-GENERATED - DO NOT EDIT MANUALLY
# ============================================================================
__dora_footer__ = {
    "component_id": "COR-FOUN-135",
    "governance_level": "critical",
    "compliance_required": True,
    "audit_trail": True,
    "dependencies": [],
    "tags": [
        "api",
        "async",
        "code-generation",
        "dataclass",
        "filesystem",
        "foundation",
        "logging",
        "messaging",
        "mocking",
        "pydantic",
    ],
    "keywords": [
        "compile",
        "compiler",
        "decorators",
        "includes",
        "module",
        "orchestrator",
        "prompt",
        "system",
    ],
    "business_value": "Provides module compiler v2 components including CompilerOutput, ModuleCompilerV2",
    "last_modified": "2026-01-24T13:02:52Z",
    "modified_by": "L9_Codegen_Engine",
    "change_summary": "Initial generation with DORA compliance",
}
# ============================================================================
# L9 DORA BLOCK - AUTO-UPDATED - DO NOT EDIT
# Runtime execution trace - updated automatically on every execution
# ============================================================================
__l9_trace__ = {
    "trace_id": "",
    "task": "",
    "timestamp": "",
    "patterns_used": [],
    "graph": {"nodes": [], "edges": []},
    "inputs": {},
    "outputs": {},
    "metrics": {"confidence": "", "errors_detected": [], "stability_score": ""},
}
# ============================================================================
# END L9 DORA BLOCK
# ============================================================================
