from __future__ import annotations

# ============================================================================
__dora_meta__ = {
    "component_name": "Api Report",
    "module_version": "1.0.0",
    "created_by": "Igor Beylin",
    "created_at": "2026-01-25T14:50:13Z",
    "updated_at": "2026-01-31T22:21:46Z",
    "layer": "operations",
    "domain": "tools",
    "module_name": "api_report",
    "type": "repository",
    "status": "active",
    "integrates_with": {
        "api_endpoints": [],
        "datasources": [],
        "memory_layers": [],
        "imported_by": [],
    },
}
# ============================================================================

from typing import TYPE_CHECKING

from .ast_scanner import scan_directories
from .filesystem import open_report, write_markdown_footer, write_markdown_header

if TYPE_CHECKING:
    from .config import SuperpackLayout


def generate_api_superpack(layout: SuperpackLayout) -> None:
    """Generate api_clients_superpack.md from AST scan of API modules."""
    output = layout.reports_dir / "api_clients_superpack.md"
    modules = scan_directories(layout.api_dirs, layout.root)

    with open_report(output) as f:
        write_markdown_header(
            f,
            "API & CLIENTS SUPERPACK",
            "T2 (Reversible)",
            "Map HTTP/RPC routes, client libraries, adapter protocols, and agent entry points.",
        )

        # Route Inventory
        f.write("## API Routes (AST Scanned)\n\n")
        f.write("| Method | Path | Handler | Module |\n")
        f.write("|--------|------|---------|--------|\n")

        routes_found = 0
        for mod in modules:
            for func in mod.functions:
                if func.is_route and func.route_method and func.route_path:
                    routes_found += 1
                    f.write(
                        f"| {func.route_method} | `{func.route_path}` | `{func.name}()` | `{mod.module_name}` |\n"
                    )

        if routes_found == 0:
            f.write("| _No routes found_ | | | |\n")

        f.write(f"\n**Total Routes:** {routes_found}\n\n")

        # Modules
        f.write("## API Modules (AST Scanned)\n\n")
        f.write("| Module | Classes | Functions | LOC |\n")
        f.write("|--------|---------|-----------|-----|\n")

        for mod in sorted(modules, key=lambda m: m.module_name):
            f.write(
                f"| `{mod.module_name}` | {len(mod.classes)} | {len(mod.functions)} | {mod.loc} |\n"
            )
        f.write("\n")

        # Adapters
        f.write("## Adapter Classes\n\n")
        for mod in modules:
            for cls in mod.classes:
                if "Adapter" in cls.name or "Client" in cls.name:
                    bases = ", ".join(cls.bases) if cls.bases else "object"
                    f.write(f"- `{mod.module_name}.{cls.name}` ({bases})\n")
        f.write("\n")

        # Change Checklist
        f.write("## Change Checklist\n\n")
        f.write("Before modifying API modules:\n\n")
        f.write("1. [ ] Update API documentation if routes change\n")
        f.write("2. [ ] Verify auth requirements\n")
        f.write("3. [ ] Update client SDK if breaking changes\n")
        f.write("4. [ ] Add integration tests for new routes\n")

        write_markdown_footer(f)


def generate_api_route_inventory(layout: SuperpackLayout) -> None:
    """Generate api_route_inventory.txt from AST scan."""
    output = layout.architecture_dir / "api_route_inventory.txt"
    modules = scan_directories(layout.api_dirs, layout.root)

    with open_report(output) as f:
        f.write("# L9 API ROUTE INVENTORY\n")
        f.write("# Auto-generated from AST scan\n\n")

        f.write("## Routes\n\n")

        for mod in sorted(modules, key=lambda m: m.module_name):
            for func in mod.functions:
                if func.is_route and func.route_method and func.route_path:
                    f.write(
                        f"{func.route_method:6} {func.route_path:30} → {mod.module_name}.{func.name}()\n"
                    )

        f.write("\n---\n")
        f.write("Auto-generated by tools/superpack_reports/\n")


# ============================================================================
# DORA FOOTER META - AUTO-GENERATED - DO NOT EDIT MANUALLY
# ============================================================================
__dora_footer__ = {
    "component_id": "TOO-OPER-032",
    "governance_level": "medium",
    "compliance_required": True,
    "audit_trail": True,
    "dependencies": [],
    "tags": ["api", "ast", "auth", "operations", "repository", "testing", "tools"],
    "keywords": ["api", "generate", "inventory", "report", "route", "superpack"],
    "business_value": "Utility module for api report",
    "last_modified": "2026-01-31T22:21:46Z",
    "modified_by": "L9_Codegen_Engine",
    "change_summary": "Initial generation with DORA compliance",
}
# ============================================================================
# L9 DORA BLOCK - AUTO-UPDATED - DO NOT EDIT
# Runtime execution trace - updated automatically on every execution
# ============================================================================
__l9_trace__ = {
    "trace_id": "",
    "task": "",
    "timestamp": "",
    "patterns_used": [],
    "graph": {"nodes": [], "edges": []},
    "inputs": {},
    "outputs": {},
    "metrics": {"confidence": "", "errors_detected": [], "stability_score": ""},
}
# ============================================================================
# END L9 DORA BLOCK
# ============================================================================
