from __future__ import annotations

# ============================================================================
__dora_meta__ = {
    "component_name": "Filesystem",
    "module_version": "1.0.0",
    "created_by": "Igor Beylin",
    "created_at": "2026-01-25T14:50:13Z",
    "updated_at": "2026-01-31T22:21:46Z",
    "layer": "operations",
    "domain": "tools",
    "module_name": "filesystem",
    "type": "utility",
    "status": "active",
    "integrates_with": {
        "api_endpoints": [],
        "datasources": [],
        "memory_layers": [],
        "imported_by": [],
    },
}
# ============================================================================

from typing import TextIO, TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path


def ensure_reports_dir(path: Path) -> None:
    """Ensure the reports directory exists."""
    path.mkdir(parents=True, exist_ok=True)


def open_report(path: Path) -> TextIO:
    """Open a report file for writing."""
    ensure_reports_dir(path.parent)
    return path.open("w", encoding="utf-8")


def write_markdown_header(f: TextIO, title: str, tier: str, description: str) -> None:
    """Write a standard superpack header."""
    f.write(f"# {title}\n\n")
    f.write(f"**Risk Tier:** {tier} | **Auto-Generated**\n\n")
    f.write("---\n\n")
    f.write(f"## Purpose\n\n{description}\n\n")
    f.write("---\n\n")


def write_markdown_footer(f: TextIO) -> None:
    """Write a standard superpack footer."""
    f.write("\n---\n\n")
    f.write(
        "*Auto-generated by `tools/superpack_reports/` | Regenerate: `make superpacks`*\n"
    )


# ============================================================================
# DORA FOOTER META - AUTO-GENERATED - DO NOT EDIT MANUALLY
# ============================================================================
__dora_footer__ = {
    "component_id": "TOO-OPER-030",
    "governance_level": "medium",
    "compliance_required": True,
    "audit_trail": True,
    "dependencies": [],
    "tags": ["filesystem", "operations", "tools", "utility"],
    "keywords": [
        "dir",
        "ensure",
        "filesystem",
        "footer",
        "header",
        "markdown",
        "open",
        "report",
    ],
    "business_value": "Utility module for filesystem",
    "last_modified": "2026-01-31T22:21:46Z",
    "modified_by": "L9_Codegen_Engine",
    "change_summary": "Initial generation with DORA compliance",
}
# ============================================================================
# L9 DORA BLOCK - AUTO-UPDATED - DO NOT EDIT
# Runtime execution trace - updated automatically on every execution
# ============================================================================
__l9_trace__ = {
    "trace_id": "",
    "task": "",
    "timestamp": "",
    "patterns_used": [],
    "graph": {"nodes": [], "edges": []},
    "inputs": {},
    "outputs": {},
    "metrics": {"confidence": "", "errors_detected": [], "stability_score": ""},
}
# ============================================================================
# END L9 DORA BLOCK
# ============================================================================
