from __future__ import annotations

from pathlib import Path
from typing import TextIO


def ensure_reports_dir(path: Path) -> None:
    """Ensure the reports directory exists."""
    path.mkdir(parents=True, exist_ok=True)


def open_report(path: Path) -> TextIO:
    """Open a report file for writing."""
    ensure_reports_dir(path.parent)
    return path.open("w", encoding="utf-8")


def write_markdown_header(f: TextIO, title: str, tier: str, description: str) -> None:
    """Write a standard superpack header."""
    f.write(f"# {title}\n\n")
    f.write(f"**Risk Tier:** {tier} | **Auto-Generated**\n\n")
    f.write("---\n\n")
    f.write(f"## Purpose\n\n{description}\n\n")
    f.write("---\n\n")


def write_markdown_footer(f: TextIO) -> None:
    """Write a standard superpack footer."""
    f.write("\n---\n\n")
    f.write(
        "*Auto-generated by `tools/superpack_reports/` | Regenerate: `make superpacks`*\n"
    )
