from __future__ import annotations

# ============================================================================
__dora_meta__ = {
    "component_name": "Tools Report",
    "module_version": "1.0.0",
    "created_by": "Igor Beylin",
    "created_at": "2026-01-25T14:50:13Z",
    "updated_at": "2026-01-31T22:21:46Z",
    "layer": "operations",
    "domain": "tools",
    "module_name": "tools_report",
    "type": "utility",
    "status": "active",
    "integrates_with": {
        "api_endpoints": [],
        "datasources": [],
        "memory_layers": [],
        "imported_by": [],
    },
}
# ============================================================================

from .ast_scanner import scan_directories
from .filesystem import open_report, write_markdown_footer, write_markdown_header
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .config import SuperpackLayout


def generate_tools_superpack(layout: SuperpackLayout) -> None:
    """Generate tools_superpack.md from AST scan."""
    output = layout.reports_dir / "tools_superpack.md"
    modules = scan_directories(layout.tools_dirs, layout.root)

    with open_report(output) as f:
        write_markdown_header(
            f,
            "TOOLS & REPORTS SUPERPACK",
            "T1 (Read-Only)",
            "Catalog utility tools, automation scripts, and reporting infrastructure.",
        )

        # Tool Modules
        f.write("## Tool Modules (AST Scanned)\n\n")
        f.write("| Module | Classes | Functions | LOC |\n")
        f.write("|--------|---------|-----------|-----|\n")

        total_loc = 0
        for mod in sorted(modules, key=lambda m: m.module_name):
            total_loc += mod.loc
            f.write(
                f"| `{mod.module_name}` | {len(mod.classes)} | {len(mod.functions)} | {mod.loc} |\n"
            )

        f.write(f"| **TOTAL** | | | **{total_loc}** |\n\n")

        # CLI Entry Points
        f.write("## CLI Entry Points\n\n")
        for mod in modules:
            for func in mod.functions:
                if func.name == "main" or "cli" in func.name.lower():
                    f.write(f"- `{mod.module_name}.{func.name}()`\n")
        f.write("\n")

        # Automation Hooks
        f.write("## Automation Hooks\n\n")
        f.write("```\n")
        f.write("Pre-commit: ruff, mypy, gitleaks (.pre-commit-config.yaml)\n")
        f.write("Makefile: lint, format, test, architecture-reports, superpacks\n")
        f.write("```\n\n")

        # Report Generation
        f.write("## Report Generation\n\n")
        f.write("```bash\n")
        f.write("make architecture-reports  # Generate architecture/*.txt\n")
        f.write("make superpacks            # Generate superpack docs\n")
        f.write("```\n")

        write_markdown_footer(f)


def generate_tools_inventory(layout: SuperpackLayout) -> None:
    """Generate tools_inventory.txt from AST scan."""
    output = layout.architecture_dir / "tools_inventory.txt"
    modules = scan_directories(layout.tools_dirs, layout.root)

    with open_report(output) as f:
        f.write("# L9 TOOLS INVENTORY\n")
        f.write("# Auto-generated from AST scan\n\n")

        for mod in sorted(modules, key=lambda m: m.module_name):
            rel_path = mod.path.relative_to(layout.root)
            f.write(f"{rel_path}\n")

            for cls in mod.classes:
                f.write(f"  class {cls.name}\n")

            for func in mod.functions:
                if not func.name.startswith("_"):
                    async_flag = "async " if func.is_async else ""
                    f.write(f"  {async_flag}def {func.name}()\n")

            f.write("\n")

        f.write("---\n")
        f.write("Auto-generated by tools/superpack_reports/\n")


# ============================================================================
# DORA FOOTER META - AUTO-GENERATED - DO NOT EDIT MANUALLY
# ============================================================================
__dora_footer__ = {
    "component_id": "TOO-OPER-031",
    "governance_level": "medium",
    "compliance_required": True,
    "audit_trail": True,
    "dependencies": [],
    "tags": ["ast", "linting", "operations", "testing", "tools", "utility"],
    "keywords": ["generate", "inventory", "report", "superpack", "tools"],
    "business_value": "Utility module for tools report",
    "last_modified": "2026-01-31T22:21:46Z",
    "modified_by": "L9_Codegen_Engine",
    "change_summary": "Initial generation with DORA compliance",
}
# ============================================================================
# L9 DORA BLOCK - AUTO-UPDATED - DO NOT EDIT
# Runtime execution trace - updated automatically on every execution
# ============================================================================
__l9_trace__ = {
    "trace_id": "",
    "task": "",
    "timestamp": "",
    "patterns_used": [],
    "graph": {"nodes": [], "edges": []},
    "inputs": {},
    "outputs": {},
    "metrics": {"confidence": "", "errors_detected": [], "stability_score": ""},
}
# ============================================================================
# END L9 DORA BLOCK
# ============================================================================
