from __future__ import annotations

from .ast_scanner import scan_directories
from .config import SuperpackLayout
from .filesystem import open_report, write_markdown_footer, write_markdown_header


def generate_tools_superpack(layout: SuperpackLayout) -> None:
    """Generate tools_superpack.md from AST scan."""
    output = layout.reports_dir / "tools_superpack.md"
    modules = scan_directories(layout.tools_dirs, layout.root)

    with open_report(output) as f:
        write_markdown_header(
            f,
            "TOOLS & REPORTS SUPERPACK",
            "T1 (Read-Only)",
            "Catalog utility tools, automation scripts, and reporting infrastructure.",
        )

        # Tool Modules
        f.write("## Tool Modules (AST Scanned)\n\n")
        f.write("| Module | Classes | Functions | LOC |\n")
        f.write("|--------|---------|-----------|-----|\n")

        total_loc = 0
        for mod in sorted(modules, key=lambda m: m.module_name):
            total_loc += mod.loc
            f.write(
                f"| `{mod.module_name}` | {len(mod.classes)} | {len(mod.functions)} | {mod.loc} |\n"
            )

        f.write(f"| **TOTAL** | | | **{total_loc}** |\n\n")

        # CLI Entry Points
        f.write("## CLI Entry Points\n\n")
        for mod in modules:
            for func in mod.functions:
                if func.name == "main" or "cli" in func.name.lower():
                    f.write(f"- `{mod.module_name}.{func.name}()`\n")
        f.write("\n")

        # Automation Hooks
        f.write("## Automation Hooks\n\n")
        f.write("```\n")
        f.write("Pre-commit: ruff, mypy, gitleaks (.pre-commit-config.yaml)\n")
        f.write("Makefile: lint, format, test, architecture-reports, superpacks\n")
        f.write("```\n\n")

        # Report Generation
        f.write("## Report Generation\n\n")
        f.write("```bash\n")
        f.write("make architecture-reports  # Generate architecture/*.txt\n")
        f.write("make superpacks            # Generate superpack docs\n")
        f.write("```\n")

        write_markdown_footer(f)


def generate_tools_inventory(layout: SuperpackLayout) -> None:
    """Generate tools_inventory.txt from AST scan."""
    output = layout.architecture_dir / "tools_inventory.txt"
    modules = scan_directories(layout.tools_dirs, layout.root)

    with open_report(output) as f:
        f.write("# L9 TOOLS INVENTORY\n")
        f.write("# Auto-generated from AST scan\n\n")

        for mod in sorted(modules, key=lambda m: m.module_name):
            rel_path = mod.path.relative_to(layout.root)
            f.write(f"{rel_path}\n")

            for cls in mod.classes:
                f.write(f"  class {cls.name}\n")

            for func in mod.functions:
                if not func.name.startswith("_"):
                    async_flag = "async " if func.is_async else ""
                    f.write(f"  {async_flag}def {func.name}()\n")

            f.write("\n")

        f.write("---\n")
        f.write("Auto-generated by tools/superpack_reports/\n")
