from __future__ import annotations

# ============================================================================
__dora_meta__ = {
    "component_name": "Workers Report",
    "module_version": "1.0.0",
    "created_by": "Igor Beylin",
    "created_at": "2026-01-25T14:50:13Z",
    "updated_at": "2026-01-31T22:21:46Z",
    "layer": "operations",
    "domain": "tools",
    "module_name": "workers_report",
    "type": "repository",
    "status": "active",
    "integrates_with": {
        "api_endpoints": [],
        "datasources": [],
        "memory_layers": ["working_memory"],
        "imported_by": [],
    },
}
# ============================================================================

from .ast_scanner import scan_directories
from .filesystem import open_report, write_markdown_footer, write_markdown_header
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .config import SuperpackLayout


def generate_orchestration_superpack(layout: SuperpackLayout) -> None:
    """Generate orchestration_superpack.md from AST scan."""
    output = layout.reports_dir / "orchestration_superpack.md"

    orch_modules = scan_directories(layout.orchestration_dirs, layout.root)
    worker_modules = scan_directories(layout.workers_dirs, layout.root)

    with open_report(output) as f:
        write_markdown_header(
            f,
            "ORCHESTRATION & WORKERS SUPERPACK",
            "T3 (High-Impact)",
            "Map orchestrator flow, worker scheduling, session lifecycle, and PacketEnvelope construction.",
        )

        # Orchestrators
        f.write("## Orchestrator Modules (AST Scanned)\n\n")
        f.write("| Module | Classes | Functions | Async | LOC |\n")
        f.write("|--------|---------|-----------|-------|-----|\n")

        for mod in sorted(orch_modules, key=lambda m: m.module_name):
            async_flag = "✓" if mod.is_async else ""
            f.write(
                f"| `{mod.module_name}` | {len(mod.classes)} | {len(mod.functions)} | {async_flag} | {mod.loc} |\n"
            )
        f.write("\n")

        # Workers
        f.write("## Worker Modules (AST Scanned)\n\n")
        f.write("| Module | Classes | Functions | LOC |\n")
        f.write("|--------|---------|-----------|-----|\n")

        for mod in sorted(worker_modules, key=lambda m: m.module_name):
            f.write(
                f"| `{mod.module_name}` | {len(mod.classes)} | {len(mod.functions)} | {mod.loc} |\n"
            )
        f.write("\n")

        # Session Lifecycle
        f.write("## Session Lifecycle\n\n")
        f.write("```\n")
        f.write("Session Creation:\n")
        f.write("  1. Create session metadata\n")
        f.write("  2. Initialize orchestrator context\n")
        f.write("  3. Bind memory substrate\n")
        f.write("  4. Set up telemetry scope\n\n")
        f.write("Session Execution:\n")
        f.write("  1. Receive PacketEnvelope\n")
        f.write("  2. Validate governance\n")
        f.write("  3. Execute kernel\n")
        f.write("  4. Emit result PacketEnvelope\n")
        f.write("  5. Write to memory\n\n")
        f.write("Session Cleanup:\n")
        f.write("  1. Flush pending writes\n")
        f.write("  2. Close memory connections\n")
        f.write("  3. Emit session-end event\n")
        f.write("```\n\n")

        # Risk Zones
        f.write("## Risk Zones\n\n")
        f.write("```\n")
        f.write("HIGH-RISK:\n")
        f.write("  ✗ websocket_orchestrator.py (protected; no edits)\n")
        f.write("  ✗ Governance bypass attempts (audit+reject)\n")
        f.write("  ✗ Worker scheduling changes (must test end-to-end)\n")
        f.write("```\n")

        write_markdown_footer(f)


def generate_worker_inventory(layout: SuperpackLayout) -> None:
    """Generate worker_inventory.txt from AST scan."""
    output = layout.architecture_dir / "worker_inventory.txt"
    modules = scan_directories(layout.workers_dirs, layout.root)

    with open_report(output) as f:
        f.write("# L9 WORKER INVENTORY\n")
        f.write("# Auto-generated from AST scan\n\n")

        f.write("## Workers\n\n")

        for mod in sorted(modules, key=lambda m: m.module_name):
            rel_path = mod.path.relative_to(layout.root)
            f.write(f"{rel_path}\n")

            for cls in mod.classes:
                f.write(f"  class {cls.name}\n")
                for method in cls.methods[:3]:
                    f.write(f"    - {method}()\n")

            for func in mod.functions:
                if not func.name.startswith("_"):
                    f.write(f"  def {func.name}()\n")

            f.write("\n")

        f.write("---\n")
        f.write("Auto-generated by tools/superpack_reports/\n")


# ============================================================================
# DORA FOOTER META - AUTO-GENERATED - DO NOT EDIT MANUALLY
# ============================================================================
__dora_footer__ = {
    "component_id": "TOO-OPER-038",
    "governance_level": "medium",
    "compliance_required": True,
    "audit_trail": True,
    "dependencies": [],
    "tags": [
        "ast",
        "event-driven",
        "operations",
        "realtime",
        "repository",
        "testing",
        "tools",
    ],
    "keywords": [
        "generate",
        "inventory",
        "orchestration",
        "report",
        "superpack",
        "worker",
        "workers",
    ],
    "business_value": "Utility module for workers report",
    "last_modified": "2026-01-31T22:21:46Z",
    "modified_by": "L9_Codegen_Engine",
    "change_summary": "Initial generation with DORA compliance",
}
# ============================================================================
# L9 DORA BLOCK - AUTO-UPDATED - DO NOT EDIT
# Runtime execution trace - updated automatically on every execution
# ============================================================================
__l9_trace__ = {
    "trace_id": "",
    "task": "",
    "timestamp": "",
    "patterns_used": [],
    "graph": {"nodes": [], "edges": []},
    "inputs": {},
    "outputs": {},
    "metrics": {"confidence": "", "errors_detected": [], "stability_score": ""},
}
# ============================================================================
# END L9 DORA BLOCK
# ============================================================================
