#!/usr/bin/env python3
"""
ADR Property-Based Test Generator

Reads ADR schemas and generates Hypothesis property tests to enforce rules.

Usage:
    python tools/test_gen/adr_property_tests.py --all
    python tools/test_gen/adr_property_tests.py --adr 0019
    python tools/test_gen/adr_property_tests.py --help

Part of GMP Phase 2 - Enhancement 3
"""

import argparse
import sys
from pathlib import Path
from typing import Any

import structlog
import yaml

logger = structlog.get_logger()


def load_adr_schema(adr_file: Path) -> dict[str, Any]:
    """Load ADR YAML schema.

    Args:
        adr_file: Path to ADR YAML file

    Returns:
        Parsed ADR schema
    """
    try:
        with open(adr_file) as f:
            return yaml.safe_load(f)
    except Exception as e:
        logger.error("adr_load_failed", file=str(adr_file), error=str(e))
        return {}


def generate_structlog_tests(adr_num: str, rules: dict[str, Any]) -> str:
    """Generate property tests for ADR-0019 (structlog).

    Args:
        adr_num: ADR number (e.g., "0019")
        rules: ADR rules from YAML

    Returns:
        Complete test file content
    """
    return '''#!/usr/bin/env python3
"""
Property-Based Tests for ADR-0019: Structlog-Only Logging

Auto-generated by tools/test_gen/adr_property_tests.py
DO NOT EDIT MANUALLY - Regenerate with: make generate-adr-tests

Exclusion strategy (aligned with .l9-allowlist.yaml):
- Skips: venv/, .venv/, current_work/, codegen/, __pycache__/, .git/, private/
- Skips: Dirs in adr_0019_print_allowed_dirs (ci/, scripts/, tools/, workflows/, etc.)
- Respects: # noqa: ADR-0019 inline suppression
- Respects: structlog.PrintLogger as a VALID structlog class (not a violation)
"""

import ast
import re
from pathlib import Path

import pytest
from hypothesis import given, strategies as st, settings, HealthCheck

import structlog

logger = structlog.get_logger()

# Directories to skip entirely — matches .l9-allowlist.yaml auto_fix_skip_dirs
SKIP_DIRS = {
    "venv", ".venv", ".git", "__pycache__", "node_modules",
    "_archived", ".backup", "current_work", ".cursor", "private",
    "codegen",
}

# Dirs where print() is allowed — matches .l9-allowlist.yaml adr_0019_print_allowed_dirs
PRINT_ALLOWED_DIRS = {
    "ci", "scripts", "tools", "workflows", "bootstrap", "examples",
    "local_dashboard",
}

# Agent dirs where print() is allowed for CLI output
PRINT_ALLOWED_AGENT_DIRS = {
    "agents/cursor",
}


def _is_excluded(path: Path) -> bool:
    """Check if path should be excluded from scanning."""
    parts = path.parts
    for part in parts:
        if part in SKIP_DIRS:
            return True
        if part.startswith(".") and part != ".":
            return True
    return False


def _is_print_allowed(rel_path: str) -> bool:
    """Check if print() is allowed in this file per allowlist."""
    for d in PRINT_ALLOWED_DIRS:
        if rel_path.startswith(d + "/") or rel_path.startswith(d + "\\\\"):
            return True
    for d in PRINT_ALLOWED_AGENT_DIRS:
        if rel_path.startswith(d + "/") or rel_path.startswith(d + "\\\\"):
            return True
    return False


def _line_has_noqa(content: str, lineno: int) -> bool:
    """Check if a specific line has # noqa: ADR-0019."""
    lines = content.splitlines()
    if 0 < lineno <= len(lines):
        return "noqa" in lines[lineno - 1] and "ADR-0019" in lines[lineno - 1]
    return False


def _get_production_files(repo_root: Path) -> list[Path]:
    """Get production Python files, excluding non-production dirs."""
    files = []
    for py_file in repo_root.rglob("*.py"):
        rel = py_file.relative_to(repo_root)
        if _is_excluded(rel):
            continue
        # Also skip test files
        if any(part.startswith("test_") or part == "tests" for part in rel.parts):
            continue
        files.append(py_file)
    return files


class TestADR0019StructlogEnforcement:
    """Property tests ensuring ADR-0019 compliance."""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup test fixtures."""
        self.repo_root = Path(__file__).parent.parent.parent
        self.production_files = _get_production_files(self.repo_root)

    def test_no_print_statements_in_production(self):
        """Property: No print() calls in production code (respects allowlist + noqa)."""
        violations = []

        for py_file in self.production_files:
            rel_path = str(py_file.relative_to(self.repo_root))

            # Skip files in print-allowed directories
            if _is_print_allowed(rel_path):
                continue

            try:
                content = py_file.read_text()
                tree = ast.parse(content, filename=str(py_file))

                for node in ast.walk(tree):
                    if isinstance(node, ast.Call):
                        if isinstance(node.func, ast.Name) and node.func.id == "print":
                            # Respect noqa suppression
                            if _line_has_noqa(content, node.lineno):
                                continue
                            violations.append({
                                "file": rel_path,
                                "line": node.lineno,
                                "violation": "print() call found"
                            })
            except SyntaxError:
                continue
            except Exception as e:
                logger.warning("parse_failed", file=str(py_file), error=str(e))

        if violations:
            msg = "\\n".join(
                f"  {v['file']}:{v['line']} - {v['violation']}"
                for v in violations
            )
            pytest.fail(f"ADR-0019 Violation: print() statements found:\\n{msg}")

    def test_no_stdlib_logging_imports(self):
        """Property: No imports from stdlib logging module (respects noqa + allowlist)."""
        violations = []

        for py_file in self.production_files:
            rel_path = str(py_file.relative_to(self.repo_root))

            # Skip files in allowlisted directories (CLI tools may use stdlib logging)
            if _is_print_allowed(rel_path):
                continue

            try:
                content = py_file.read_text()
                tree = ast.parse(content, filename=str(py_file))

                for node in ast.walk(tree):
                    # Check for: import logging
                    if isinstance(node, ast.Import):
                        for alias in node.names:
                            if alias.name == "logging":
                                if _line_has_noqa(content, node.lineno):
                                    continue
                                violations.append({
                                    "file": str(py_file.relative_to(self.repo_root)),
                                    "line": node.lineno,
                                    "violation": f"import {alias.name}"
                                })

                    # Check for: from logging import X
                    if isinstance(node, ast.ImportFrom):
                        if node.module == "logging":
                            if _line_has_noqa(content, node.lineno):
                                continue
                            violations.append({
                                "file": str(py_file.relative_to(self.repo_root)),
                                "line": node.lineno,
                                "violation": f"from logging import ..."
                            })
            except SyntaxError:
                continue
            except Exception as e:
                logger.warning("parse_failed", file=str(py_file), error=str(e))

        if violations:
            msg = "\\n".join(
                f"  {v['file']}:{v['line']} - {v['violation']}"
                for v in violations
            )
            pytest.fail(f"ADR-0019 Violation: stdlib logging imports found:\\n{msg}")

    def test_structlog_logger_pattern(self):
        """Property: Verify structlog.get_logger() is used correctly."""
        compliant_files = []

        for py_file in self.production_files:
            try:
                content = py_file.read_text()

                # Check for structlog usage
                if "structlog" not in content:
                    continue

                # Check for correct pattern: logger = structlog.get_logger()
                if re.search(r'logger\\s*=\\s*structlog\\.get_logger\\(\\)', content):
                    compliant_files.append(str(py_file.relative_to(self.repo_root)))

            except Exception as e:
                logger.warning("pattern_check_failed", file=str(py_file), error=str(e))

        logger.info("structlog_pattern_check", compliant_files=len(compliant_files))

        # This is informational - not a hard failure
        assert len(compliant_files) >= 0, "Sanity check"

    @given(st.text(min_size=10, max_size=500))
    @settings(
        max_examples=200,
        suppress_health_check=[HealthCheck.function_scoped_fixture]
    )
    def test_code_samples_no_print(self, code_sample: str):
        """Fuzz test: Random code samples should not contain print()."""
        # Skip if not valid Python
        try:
            tree = ast.parse(code_sample)
        except SyntaxError:
            return  # Invalid syntax is fine for fuzzing

        # Check for print calls
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name) and node.func.id == "print":
                    pytest.fail(
                        f"Fuzz test found print() in generated code:\\n{code_sample[:100]}"
                    )

    @given(st.text(min_size=20, max_size=200, alphabet=st.characters(whitelist_categories=("Lu", "Ll"))))
    @settings(max_examples=100)
    def test_log_context_binding(self, context_key: str):
        """Property test: Structlog context binding should work with any string key."""
        try:
            log = structlog.get_logger()
            bound = log.bind(**{context_key: "test_value"})

            # Verify binding worked
            assert bound is not None

        except Exception as e:
            # Some keys might be invalid, that's fine
            if "invalid" not in str(e).lower():
                pytest.fail(f"Unexpected error binding context key '{context_key}': {e}")


class TestADR0019Regressions:
    """Regression tests for known ADR-0019 violations."""

    def test_no_printlogger_usage(self):
        """Regression: PrintLogger was removed per ADR-0019.

        Note: structlog.PrintLogger is a VALID structlog class and is NOT a violation.
        Only flags non-structlog PrintLogger references.
        """
        repo_root = Path(__file__).parent.parent.parent

        violations = []
        for py_file in _get_production_files(repo_root):
            try:
                content = py_file.read_text()
                if "PrintLogger" in content or "print_logger" in content:
                    # structlog.PrintLogger is valid — not a violation
                    if "structlog.PrintLogger" in content or "structlog._output" in content:
                        continue
                    violations.append(str(py_file.relative_to(repo_root)))
            except Exception:
                continue

        assert not violations, f"PrintLogger found in: {violations}"

    def test_ci_check_adr_compliance_uses_structlog(self):
        """Regression: CI compliance checker must use structlog.

        Note: CI tools are CLI tools — print() for final output is acceptable.
        This test only checks that structlog is imported (not print count).
        """
        ci_check = Path(__file__).parent.parent.parent / "ci" / "check_adr_compliance.py"

        if not ci_check.exists():
            pytest.skip("CI compliance checker not found")

        content = ci_check.read_text()

        # Must import structlog
        assert "import structlog" in content, "CI checker missing structlog import"

        # CI tools are in adr_0019_print_allowed_dirs — print() is acceptable
        # Just verify structlog is the primary logging mechanism
        assert "structlog.get_logger" in content or "structlog.stdlib" in content, \\
            "CI checker should use structlog for logging (print for CLI output is OK)"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''


def generate_packet_envelope_tests(adr_num: str, rules: dict[str, Any]) -> str:
    """Generate property tests for ADR-0006 (PacketEnvelope).

    Args:
        adr_num: ADR number
        rules: ADR rules from YAML

    Returns:
        Complete test file content
    """
    return '''#!/usr/bin/env python3
"""
Property-Based Tests for ADR-0006: PacketEnvelope Audit Trails

Auto-generated by tools/test_gen/adr_property_tests.py
"""

import ast
from pathlib import Path

import pytest
from hypothesis import given, strategies as st, settings

import structlog

logger = structlog.get_logger()


class TestADR0006PacketEnvelopeUsage:
    """Property tests for PacketEnvelope audit trail compliance."""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup test fixtures."""
        self.repo_root = Path(__file__).parent.parent.parent

    def test_all_kernels_use_packet_envelope(self):
        """Property: All kernel files must use PacketEnvelope for processing."""
        kernel_files = list((self.repo_root / "core").glob("*_kernel.py"))
        kernel_files.extend((self.repo_root / "kernels").rglob("*.py"))

        violations = []

        for kernel_file in kernel_files:
            if "__pycache__" in str(kernel_file):
                continue

            try:
                content = kernel_file.read_text()

                # Must import PacketEnvelope
                if "PacketEnvelope" not in content and "from core.packet_envelope" not in content:
                    violations.append({
                        "file": str(kernel_file.relative_to(self.repo_root)),
                        "violation": "Missing PacketEnvelope import"
                    })

            except Exception as e:
                logger.warning("kernel_check_failed", file=str(kernel_file), error=str(e))

        if violations:
            msg = "\\n".join(f"  {v['file']}: {v['violation']}" for v in violations)
            pytest.fail(f"ADR-0006 Violation:\\n{msg}")

    @given(st.text(min_size=5, max_size=50))
    @settings(max_examples=50)
    def test_packet_envelope_metadata_keys(self, key: str):
        """Property test: PacketEnvelope should handle arbitrary metadata keys."""
        # This is a placeholder - would need actual PacketEnvelope import
        # to test properly. Shows the pattern.

        # Validate key is safe
        assert isinstance(key, str)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''


def emit_test_file(adr_num: str, test_code: str, output_dir: Path) -> Path:
    """Write generated test file to disk.

    Args:
        adr_num: ADR number (e.g., "0019")
        test_code: Complete test file content
        output_dir: Output directory (tests/generated/)

    Returns:
        Path to written test file
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    test_file = output_dir / f"test_adr_{adr_num}_properties.py"
    test_file.write_text(test_code)

    logger.info("test_file_generated", path=str(test_file))
    return test_file


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Generate property-based tests from ADR schemas"
    )
    parser.add_argument(
        "--repo-root", type=Path, default=Path("."), help="Repository root directory"
    )
    parser.add_argument(
        "--adr", type=str, help="Generate tests for specific ADR (e.g., '0019')"
    )
    parser.add_argument(
        "--all", action="store_true", help="Generate tests for all ADRs"
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    adr_dir = repo_root / "readme" / "adr" / "rules"
    output_dir = repo_root / "tests" / "generated"

    # Define generators for specific ADRs
    generators = {
        "0019": generate_structlog_tests,
        "0006": generate_packet_envelope_tests,
    }

    if args.adr:
        # Generate for specific ADR
        if args.adr not in generators:
            logger.error("no_generator", adr=args.adr)
            print(f"❌ No test generator for ADR-{args.adr}")
            return 1

        adr_file = adr_dir / f"{args.adr}.yaml"
        if not adr_file.exists():
            logger.warning("adr_file_not_found", path=str(adr_file))
            rules = {}
        else:
            rules = load_adr_schema(adr_file)

        generator = generators[args.adr]
        test_code = generator(args.adr, rules)
        test_file = emit_test_file(args.adr, test_code, output_dir)

        print(f"✅ Generated: {test_file}")

    elif args.all:
        # Generate for all supported ADRs
        generated = []
        for adr_num, generator in generators.items():
            adr_file = adr_dir / f"{adr_num}.yaml"
            rules = load_adr_schema(adr_file) if adr_file.exists() else {}

            test_code = generator(adr_num, rules)
            test_file = emit_test_file(adr_num, test_code, output_dir)
            generated.append(test_file)

        print(f"\n✅ Generated {len(generated)} ADR property test files:")
        for f in generated:
            print(f"   {f.relative_to(repo_root)}")

    else:
        parser.print_help()
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
