class ExecutorBuilder:
    def __init__(...):
        self.stages = []
        self.policies = []

    def with_prompt_defense(...): ...
    def with_memory_warming(...): ...
    def with_reflection(...): ...
