class ToolBindingService(Protocol):
    def ensure_bound(self, instance, tool_call) -> None: ...

class ToolExecutionStrategy(Protocol):
    async def execute(self, instance, tool_call, memory_ctx) -> ToolCallResult: ...

class ToolAuditService(Protocol):
    async def record_success(...): ...
    async def record_failure(...): ...
